// Self-contained HTML renderer for the M5 option A weekly digest card.
//
// One callsite (`week::run` with `--format html`) builds a `WeekHtmlStats`
// out of the existing `WeekStats` plus a couple of derived aggregates,
// then hands it to `render_card`. The output is a complete
// `<!DOCTYPE html>` document with inline `<style>` (no JS, no external
// fonts, no images, no SVG). Designed to drop straight into a Slack DM,
// Notion page, or attached `.html` file.
//
// We deliberately don't pull in askama / minijinja / handlebars: this is
// one template, and `format!` macros plus a tiny HTML escaper are
// cheaper to maintain than a build-time templating dep.

use chrono::NaiveDate;
use fluxmirror_core::report::LangPack;

use super::git_narrative::GitNarrative;

/// One row in the per-agent summary table.
#[derive(Debug, Clone)]
pub struct AgentRow {
    pub agent: String,
    pub calls: u64,
    pub sessions: u64,
    pub active_days: u64,
    pub top_tool: String,
}

/// All data the HTML card needs to render. Built by `week::run` from
/// the existing `WeekStats` collector plus a small derivation pass that
/// fills the heatmap matrix and the busiest-day / heaviest-tool fields.
#[derive(Debug, Clone)]
pub struct WeekHtmlStats {
    pub range_start: NaiveDate,
    pub range_end: NaiveDate,
    pub tz_label: String,
    /// `[day_of_week][hour_of_day]` calls. day_of_week is 0=Monday..6=Sunday.
    pub heatmap: [[u32; 24]; 7],
    pub agent_summary: Vec<AgentRow>,
    /// `(path, count)` — at most 10 rows.
    pub top_files: Vec<(String, u32)>,
    /// `(command snippet, count)` — at most 10 rows.
    pub top_shells: Vec<(String, u32)>,
    /// 0=Monday..6=Sunday — index into `lp.html_dow_labels` for the
    /// "busiest day" sentence.
    pub busiest_day_dow: u8,
    pub busiest_day_calls: u32,
    pub heaviest_tool: String,
    pub heaviest_tool_calls: u32,
    pub total_calls: u32,
    pub total_agents: usize,
    /// `Generated by fluxmirror v0.5.7 · 2026-04-27T14:12:00Z` — the
    /// caller passes a pre-formatted string so tests can pin it to a
    /// deterministic value.
    pub generated_footer: String,
    /// "Shipped this week" git narrative. `None` when collection was
    /// disabled via `--no-git-narrative`; `Some(empty)` when the pass
    /// ran but no commits landed in any cwd's repo. The renderer omits
    /// the section in both cases.
    pub narrative: Option<GitNarrative>,
}

/// Escape a string for safe HTML text/attribute interpolation.
///
/// Covers the five entities required by HTML5 in normal text + attribute
/// contexts: `& < > " '`. Single-pass, allocates only when escaping is
/// needed. Anything more elaborate (control chars, NBSP, etc.) isn't
/// in our threat model — this output is rendered locally from data the
/// user themselves recorded.
pub fn html_escape(s: &str) -> String {
    let needs_escape = s
        .bytes()
        .any(|b| matches!(b, b'&' | b'<' | b'>' | b'"' | b'\''));
    if !needs_escape {
        return s.to_string();
    }
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            other => out.push(other),
        }
    }
    out
}

/// Replace every `{name}` placeholder in `template` from the `vars`
/// `(key, value)` slice. Tiny on purpose — we only need this for the
/// summary sentence and we don't want to bring in `strfmt` or similar
/// for one render.
pub fn replace_all(template: &str, vars: &[(&str, &str)]) -> String {
    let mut out = template.to_string();
    for (k, v) in vars {
        let placeholder = format!("{{{}}}", k);
        out = out.replace(&placeholder, v);
    }
    out
}

/// Bucket a per-cell call count to one of five color steps. Returns the
/// inline `background:` value for the cell. `0` is rendered as a
/// near-transparent gray so the grid shape stays visible without
/// suggesting activity. The accent color is a single blue (#3b82f6) at
/// four lightness steps.
fn heatmap_color(count: u32) -> &'static str {
    match count {
        0 => "#f3f4f6",       // gray-100 (empty cell)
        1..=2 => "#dbeafe",   // blue-100
        3..=5 => "#93c5fd",   // blue-300
        6..=20 => "#3b82f6",  // blue-500 (accent)
        _ => "#1d4ed8",       // blue-700 (heavy)
    }
}

/// Render the entire HTML card. Returns a complete document starting
/// with `<!DOCTYPE html>`.
pub fn render_card(stats: &WeekHtmlStats, lp: &LangPack) -> String {
    // Pre-allocate roughly enough room for the document; the heatmap is
    // 168 cells and dominates the size.
    let mut out = String::with_capacity(16 * 1024);

    let title = html_escape(lp.html_title);
    let range_line = format!(
        "{} - {} &middot; {}",
        stats.range_start.format("%b %d"),
        stats.range_end.format("%b %d, %Y"),
        html_escape(&stats.tz_label)
    );

    out.push_str("<!DOCTYPE html>\n");
    out.push_str("<html lang=\"en\">\n");
    out.push_str("<head>\n");
    out.push_str("<meta charset=\"utf-8\">\n");
    out.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    out.push_str(&format!("<title>{}</title>\n", title));
    out.push_str("<style>\n");
    out.push_str(INLINE_CSS);
    out.push_str("</style>\n");
    out.push_str("</head>\n");
    out.push_str("<body>\n");
    out.push_str("<main class=\"card\">\n");

    // Header.
    out.push_str("<header class=\"hd\">\n");
    out.push_str(&format!("<h1>{}</h1>\n", title));
    out.push_str(&format!("<p class=\"sub\">{}</p>\n", range_line));
    out.push_str("</header>\n");

    // Heatmap section.
    render_heatmap(&mut out, stats, lp);

    // Top files / top shells two-column block.
    out.push_str("<section class=\"two-col\">\n");
    render_top_table(
        &mut out,
        lp.html_top_files_heading,
        lp.html_item_count_columns,
        &stats.top_files,
    );
    render_top_table(
        &mut out,
        lp.html_top_shells_heading,
        lp.html_item_count_columns,
        &stats.top_shells,
    );
    out.push_str("</section>\n");

    // Per-agent summary.
    render_agent_table(&mut out, stats, lp);

    // "Shipped this week" git narrative — sits between the data-only
    // sections and the summary so the human signal lands close to the
    // closing paragraph.
    render_narrative(&mut out, stats, lp);

    // Summary paragraph.
    render_summary(&mut out, stats, lp);

    // Footer.
    out.push_str(&format!(
        "<footer class=\"ft\">{}</footer>\n",
        html_escape(&stats.generated_footer)
    ));
    out.push_str("</main>\n");
    out.push_str("</body>\n");
    out.push_str("</html>\n");
    out
}

fn render_heatmap(out: &mut String, stats: &WeekHtmlStats, lp: &LangPack) {
    out.push_str("<section class=\"hm\">\n");
    out.push_str(&format!(
        "<h2>{}</h2>\n",
        html_escape(lp.html_heatmap_heading)
    ));
    out.push_str(&format!(
        "<p class=\"axis\">{}</p>\n",
        html_escape(lp.html_hour_axis_label)
    ));
    out.push_str("<div class=\"grid\">\n");

    // Header row: empty corner cell + 24 hour columns.
    out.push_str("<div class=\"hcell hdr\"></div>\n");
    for h in 0..24u32 {
        out.push_str(&format!("<div class=\"hcell hdr\">{:02}</div>\n", h));
    }

    // Seven rows.
    for dow in 0..7usize {
        let label = lp.html_dow_labels[dow];
        out.push_str(&format!(
            "<div class=\"hcell rowlbl\">{}</div>\n",
            html_escape(label)
        ));
        for h in 0..24usize {
            let n = stats.heatmap[dow][h];
            let bg = heatmap_color(n);
            // The data attribute lets curious power users still grok the
            // grid via devtools without us having to ship JS.
            out.push_str(&format!(
                "<div class=\"hcell\" style=\"background:{};\" data-count=\"{}\" title=\"{} {:02}:00 - {} calls\"></div>\n",
                bg,
                n,
                html_escape(label),
                h,
                n
            ));
        }
    }

    out.push_str("</div>\n");
    out.push_str("</section>\n");
}

fn render_top_table(
    out: &mut String,
    heading: &str,
    cols: [&'static str; 2],
    rows: &[(String, u32)],
) {
    out.push_str("<section class=\"tt\">\n");
    out.push_str(&format!("<h2>{}</h2>\n", html_escape(heading)));
    if rows.is_empty() {
        out.push_str("<p class=\"empty\">&mdash;</p>\n");
        out.push_str("</section>\n");
        return;
    }
    out.push_str("<table>\n<thead><tr>\n");
    out.push_str(&format!(
        "<th>{}</th><th class=\"num\">{}</th>\n",
        html_escape(cols[0]),
        html_escape(cols[1])
    ));
    out.push_str("</tr></thead>\n<tbody>\n");
    for (item, count) in rows.iter().take(10) {
        out.push_str(&format!(
            "<tr><td class=\"item\">{}</td><td class=\"num\">{}</td></tr>\n",
            html_escape(item),
            count
        ));
    }
    out.push_str("</tbody>\n</table>\n");
    out.push_str("</section>\n");
}

fn render_agent_table(out: &mut String, stats: &WeekHtmlStats, lp: &LangPack) {
    out.push_str("<section class=\"ag\">\n");
    out.push_str(&format!(
        "<h2>{}</h2>\n",
        html_escape(lp.html_per_agent_heading)
    ));
    if stats.agent_summary.is_empty() {
        out.push_str("<p class=\"empty\">&mdash;</p>\n");
        out.push_str("</section>\n");
        return;
    }
    out.push_str("<table>\n<thead><tr>\n");
    for c in lp.html_agent_columns {
        out.push_str(&format!("<th>{}</th>\n", html_escape(c)));
    }
    out.push_str("</tr></thead>\n<tbody>\n");
    for row in &stats.agent_summary {
        out.push_str(&format!(
            "<tr><td>{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td>{}</td></tr>\n",
            html_escape(&row.agent),
            row.calls,
            row.sessions,
            row.active_days,
            html_escape(&row.top_tool),
        ));
    }
    out.push_str("</tbody>\n</table>\n");
    out.push_str("</section>\n");
}

/// Render the "Shipped this week" git-narrative section.
///
/// Omits the entire `<section>` when the narrative is missing or empty
/// — the visual rule is "if there's nothing to ship, don't tease".
fn render_narrative(out: &mut String, stats: &WeekHtmlStats, lp: &LangPack) {
    let narrative = match stats.narrative.as_ref() {
        Some(n) if !n.repos.is_empty() => n,
        _ => return,
    };

    out.push_str("<section class=\"narrative\">\n");
    out.push_str(&format!(
        "<h2>{}</h2>\n",
        html_escape(lp.html_narrative_heading)
    ));
    for repo in &narrative.repos {
        let count_label = if repo.total_commits == 1 {
            lp.html_narrative_count_one.to_string()
        } else {
            lp.html_narrative_count_many
                .replace("{n}", &repo.total_commits.to_string())
        };
        out.push_str("<article>\n");
        out.push_str("<header>\n");
        out.push_str(&format!(
            "<span class=\"repo-name\">&#128193; {}</span>\n",
            html_escape(&repo.repo_name)
        ));
        out.push_str(&format!(
            "<span class=\"commit-count\">{}</span>\n",
            html_escape(&count_label)
        ));
        out.push_str("</header>\n");
        out.push_str("<ul>\n");
        for subject in &repo.commits {
            out.push_str(&format!("<li>{}</li>\n", html_escape(subject)));
        }
        out.push_str("</ul>\n");
        out.push_str("</article>\n");
    }
    out.push_str("</section>\n");
}

fn render_summary(out: &mut String, stats: &WeekHtmlStats, lp: &LangPack) {
    out.push_str("<section class=\"sm\">\n");
    out.push_str(&format!(
        "<h2>{}</h2>\n",
        html_escape(lp.html_summary_heading)
    ));
    let body = if stats.total_calls == 0 {
        lp.html_summary_empty.to_string()
    } else {
        let dow_label = lp
            .html_dow_labels
            .get(stats.busiest_day_dow as usize)
            .copied()
            .unwrap_or("?");
        let calls_str = stats.total_calls.to_string();
        let agents_str = stats.total_agents.to_string();
        let dow_calls_str = stats.busiest_day_calls.to_string();
        let tool_calls_str = stats.heaviest_tool_calls.to_string();
        replace_all(
            lp.html_summary_template,
            &[
                ("calls", calls_str.as_str()),
                ("agents", agents_str.as_str()),
                ("dow", dow_label),
                ("dow_calls", dow_calls_str.as_str()),
                ("tool", stats.heaviest_tool.as_str()),
                ("tool_calls", tool_calls_str.as_str()),
            ],
        )
    };
    out.push_str(&format!("<p>{}</p>\n", html_escape(&body)));
    out.push_str("</section>\n");
}

/// Inline CSS for the card. Conservative palette: one accent blue plus a
/// neutral gray scale. No `@font-face`, no `url(...)` references — the
/// only thing the browser needs to render this file is itself.
const INLINE_CSS: &str = r#"
*, *::before, *::after { box-sizing: border-box; }
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  background: #f9fafb;
  color: #111827;
  line-height: 1.45;
  padding: 24px 12px;
}
.card {
  max-width: 960px;
  margin: 0 auto;
  background: #ffffff;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  padding: 32px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
}
.hd h1 { margin: 0; font-size: 1.6rem; color: #1d4ed8; }
.hd .sub { margin: 4px 0 24px 0; color: #6b7280; font-size: 0.95rem; }
section { margin-bottom: 28px; }
section h2 { font-size: 1.05rem; margin: 0 0 12px 0; color: #111827; }
.axis { margin: 0 0 8px 0; color: #6b7280; font-size: 0.8rem; }
.grid {
  display: grid;
  grid-template-columns: 36px repeat(24, 1fr);
  gap: 2px;
}
.hcell {
  height: 18px;
  border-radius: 2px;
  font-size: 0.65rem;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #6b7280;
}
.hcell.hdr { background: transparent; }
.hcell.rowlbl { justify-content: flex-start; padding-left: 2px; color: #374151; }
.two-col {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
}
@media (max-width: 640px) {
  .two-col { grid-template-columns: 1fr; }
  .grid { grid-template-columns: 28px repeat(24, 1fr); }
}
table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
th { font-weight: 600; background: #f3f4f6; color: #374151; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
td.item { font-family: ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace; font-size: 0.85rem; word-break: break-all; }
.empty { color: #9ca3af; margin: 0; }
.sm p { font-size: 0.95rem; color: #1f2937; margin: 0; }
.ft { color: #9ca3af; font-size: 0.75rem; text-align: right; margin-top: 16px; }
.narrative article {
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 12px 14px;
  margin-bottom: 12px;
}
.narrative article:last-child { margin-bottom: 0; }
.narrative article > header {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  margin-bottom: 8px;
  gap: 12px;
}
.narrative .repo-name {
  font-weight: 600;
  color: #111827;
  font-size: 0.95rem;
}
.narrative .commit-count {
  color: #6b7280;
  font-size: 0.8rem;
  font-variant-numeric: tabular-nums;
  text-align: right;
}
.narrative ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
.narrative li {
  font-family: ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace;
  font-size: 0.8rem;
  color: #1f2937;
  padding: 3px 0;
  border-top: 1px dashed #e5e7eb;
  word-break: break-word;
}
.narrative li:first-child { border-top: none; }
"#;

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_stats() -> WeekHtmlStats {
        let mut heatmap = [[0u32; 24]; 7];
        heatmap[1][14] = 7; // Tuesday 14:00, busy
        heatmap[3][9] = 3;
        WeekHtmlStats {
            range_start: NaiveDate::from_ymd_opt(2026, 4, 21).unwrap(),
            range_end: NaiveDate::from_ymd_opt(2026, 4, 27).unwrap(),
            tz_label: "Asia/Seoul".into(),
            heatmap,
            agent_summary: vec![AgentRow {
                agent: "claude-code".into(),
                calls: 10,
                sessions: 2,
                active_days: 2,
                top_tool: "Bash".into(),
            }],
            top_files: vec![("src/foo.rs".into(), 4)],
            top_shells: vec![("cargo test".into(), 2)],
            busiest_day_dow: 1,
            busiest_day_calls: 7,
            heaviest_tool: "Bash".into(),
            heaviest_tool_calls: 6,
            total_calls: 10,
            total_agents: 1,
            generated_footer: "Generated by fluxmirror v0.5.7 - 2026-04-27T00:00:00Z".into(),
            narrative: None,
        }
    }

    #[test]
    fn html_escape_preserves_ascii() {
        assert_eq!(html_escape("foo bar"), "foo bar");
    }

    #[test]
    fn html_escape_handles_all_five_entities() {
        assert_eq!(
            html_escape("a&b<c>d\"e'f"),
            "a&amp;b&lt;c&gt;d&quot;e&#39;f"
        );
    }

    #[test]
    fn replace_all_substitutes_each_placeholder() {
        let s = replace_all("hi {name}, you have {n} new messages", &[
            ("name", "alice"),
            ("n", "3"),
        ]);
        assert_eq!(s, "hi alice, you have 3 new messages");
    }

    #[test]
    fn heatmap_color_buckets_match_thresholds() {
        assert_eq!(heatmap_color(0), "#f3f4f6");
        assert_eq!(heatmap_color(1), "#dbeafe");
        assert_eq!(heatmap_color(2), "#dbeafe");
        assert_eq!(heatmap_color(5), "#93c5fd");
        assert_eq!(heatmap_color(20), "#3b82f6");
        assert_eq!(heatmap_color(21), "#1d4ed8");
        assert_eq!(heatmap_color(999), "#1d4ed8");
    }

    #[test]
    fn render_card_starts_with_doctype_and_closes_html() {
        let lp = fluxmirror_core::report::pack("english");
        let s = render_card(&fixture_stats(), lp);
        assert!(s.starts_with("<!DOCTYPE html>"), "got: {}", &s[..50]);
        assert!(s.contains("</html>"));
        assert!(s.contains("fluxmirror weekly digest"));
    }

    #[test]
    fn render_card_emits_168_data_cells() {
        let lp = fluxmirror_core::report::pack("english");
        let s = render_card(&fixture_stats(), lp);
        // Data cells carry `data-count="..."`; header cells do not.
        let cell_count = s.matches("data-count=\"").count();
        assert_eq!(cell_count, 24 * 7, "expected 168 data cells");
    }

    #[test]
    fn render_card_korean_uses_translated_strings() {
        let lp = fluxmirror_core::report::pack("korean");
        let s = render_card(&fixture_stats(), lp);
        assert!(s.contains("주간 다이제스트"), "missing ko title");
        assert!(s.contains("활동 히트맵"), "missing ko heatmap heading");
        assert!(s.contains("화"), "missing ko Tuesday label");
    }

    #[test]
    fn render_card_summary_substitutes_placeholders() {
        let lp = fluxmirror_core::report::pack("english");
        let s = render_card(&fixture_stats(), lp);
        assert!(s.contains("10 calls"), "missing call count in summary");
        assert!(s.contains("Tue"), "missing day label in summary");
        assert!(s.contains("7 calls"), "missing busiest-day calls");
        assert!(s.contains("Bash"), "missing heaviest tool");
    }

    #[test]
    fn render_card_empty_uses_summary_empty_line() {
        let lp = fluxmirror_core::report::pack("english");
        let mut stats = fixture_stats();
        stats.total_calls = 0;
        stats.total_agents = 0;
        stats.agent_summary.clear();
        stats.top_files.clear();
        stats.top_shells.clear();
        stats.heatmap = [[0; 24]; 7];
        let s = render_card(&stats, lp);
        assert!(s.contains("No agent activity recorded"));
    }

    #[test]
    fn render_card_escapes_user_supplied_paths() {
        let lp = fluxmirror_core::report::pack("english");
        let mut stats = fixture_stats();
        stats.top_files = vec![("<script>".into(), 1)];
        let s = render_card(&stats, lp);
        assert!(!s.contains("<script>"), "raw script tag leaked");
        assert!(s.contains("&lt;script&gt;"), "expected escaped form");
    }

    #[test]
    fn render_card_narrative_section_renders_repo_and_commits() {
        use crate::cmd::report::git_narrative::{GitNarrative, RepoCommits};
        let lp = fluxmirror_core::report::pack("english");
        let mut stats = fixture_stats();
        stats.narrative = Some(GitNarrative {
            repos: vec![
                RepoCommits {
                    repo_name: "fluxmirror".into(),
                    repo_path: std::path::PathBuf::from("/tmp/fluxmirror"),
                    commits: vec![
                        "feat: alpha".into(),
                        "fix: beta".into(),
                        "docs: gamma".into(),
                    ],
                    total_commits: 3,
                },
                RepoCommits {
                    repo_name: "discord-claude-bot".into(),
                    repo_path: std::path::PathBuf::from("/tmp/discord-claude-bot"),
                    commits: vec!["feat: lone".into()],
                    total_commits: 1,
                },
            ],
        });
        let s = render_card(&stats, lp);
        assert!(s.contains("class=\"narrative\""), "missing narrative class");
        assert!(s.contains("Shipped this week"), "missing heading");
        assert!(s.contains("fluxmirror"), "missing repo name");
        assert!(s.contains("discord-claude-bot"), "missing second repo");
        assert!(s.contains("feat: alpha"), "missing first commit");
        assert!(s.contains("fix: beta"));
        assert!(s.contains("docs: gamma"));
        assert!(s.contains("feat: lone"));
        assert!(s.contains("3 commits"), "missing plural badge");
        assert!(s.contains("1 commit"), "missing singular badge");
    }

    #[test]
    fn render_card_narrative_omitted_when_empty() {
        use crate::cmd::report::git_narrative::GitNarrative;
        let lp = fluxmirror_core::report::pack("english");
        let mut stats = fixture_stats();
        stats.narrative = Some(GitNarrative { repos: vec![] });
        let s = render_card(&stats, lp);
        assert!(
            !s.contains("class=\"narrative\""),
            "empty narrative should not emit a section"
        );
        assert!(!s.contains("Shipped this week"));
    }

    #[test]
    fn render_card_narrative_omitted_when_none() {
        let lp = fluxmirror_core::report::pack("english");
        let stats = fixture_stats(); // narrative: None
        let s = render_card(&stats, lp);
        assert!(!s.contains("class=\"narrative\""));
        assert!(!s.contains("Shipped this week"));
    }

    #[test]
    fn render_card_narrative_korean_heading() {
        use crate::cmd::report::git_narrative::{GitNarrative, RepoCommits};
        let lp = fluxmirror_core::report::pack("korean");
        let mut stats = fixture_stats();
        stats.narrative = Some(GitNarrative {
            repos: vec![RepoCommits {
                repo_name: "fluxmirror".into(),
                repo_path: std::path::PathBuf::from("/tmp/fluxmirror"),
                commits: vec!["feat: only".into()],
                total_commits: 1,
            }],
        });
        let s = render_card(&stats, lp);
        assert!(s.contains("이번 주 출하"), "missing ko narrative heading");
        assert!(s.contains("커밋 1개"), "missing ko singular badge");
    }

    #[test]
    fn render_card_narrative_escapes_commit_subjects() {
        use crate::cmd::report::git_narrative::{GitNarrative, RepoCommits};
        let lp = fluxmirror_core::report::pack("english");
        let mut stats = fixture_stats();
        stats.narrative = Some(GitNarrative {
            repos: vec![RepoCommits {
                repo_name: "evil<repo>".into(),
                repo_path: std::path::PathBuf::from("/tmp/evil"),
                commits: vec!["feat: <script>alert(1)</script>".into()],
                total_commits: 1,
            }],
        });
        let s = render_card(&stats, lp);
        assert!(!s.contains("<script>alert"), "raw script leaked");
        assert!(s.contains("&lt;script&gt;"), "expected escaped form");
        assert!(s.contains("evil&lt;repo&gt;"));
    }
}
