// Shared HTML output plumbing for the report subcommands.
//
// Three concerns live here:
//
//   - `generated_footer()` — produce the "Generated by fluxmirror v… ·
//     <ts>" line every card carries in its `<footer>`.
//   - `emit_html()` — resolve the `--out` argument into the right
//     destination (stdout, explicit file, or auto-out under /tmp) and
//     write the rendered card. Returns the binary's `ExitCode`.
//   - `auto_out_path()` — the timestamp-suffixed `/tmp` path used when
//     the user passes `--html` (or `--format html`) without `--out`.
//
// Centralised so the today / yesterday / week / agent / compare paths
// all share the same UX (timestamped filename, stdout sentinel, exit
// code 2 on write failure).

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use chrono::Utc;

use crate::cmd::util::{err_exit2, scrub_for_output};

/// Pre-formatted footer line. Pinned to the binary version + an UTC
/// instant so the card's footer reads exactly the same shape as the
/// weekly card. Tests that need determinism build their own footer.
pub fn generated_footer() -> String {
    format!(
        "Generated by fluxmirror v{} - {}",
        env!("CARGO_PKG_VERSION"),
        Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true)
    )
}

/// Resolve `--out` and write the rendered HTML.
///
/// Routing rules (mirror M5.4 spec):
///   - `out = None` → write to `/tmp/fluxmirror-<subcmd>-<ts>.html`,
///     print the absolute path on stdout.
///   - `out = Some("-")` → write the HTML to stdout (raw, no path line).
///   - `out = Some(path)` → write to `path`, print
///     `wrote <abs path> (<n> bytes)` on stdout.
///
/// The HTML body is pattern-scrubbed against the active redaction rules
/// before any byte hits stdout / disk. The capture binary's `events.db`
/// stays untouched — scrubbing is purely a presentation-layer step.
pub fn emit_html(subcmd: &str, html: String, out: Option<&Path>) -> ExitCode {
    let html = scrub_for_output(&html);
    match out {
        None => {
            // Auto-out path: timestamp-suffixed under /tmp.
            let path = auto_out_path(subcmd);
            match std::fs::write(&path, html.as_bytes()) {
                Ok(()) => {
                    println!("wrote {}", path.display());
                    ExitCode::SUCCESS
                }
                Err(e) => err_exit2(format!(
                    "fluxmirror {subcmd}: writing {}: {e}",
                    path.display()
                )),
            }
        }
        Some(path) if is_stdout_sentinel(path) => {
            print!("{}", html);
            ExitCode::SUCCESS
        }
        Some(path) => match std::fs::write(path, html.as_bytes()) {
            Ok(()) => {
                println!("wrote {} ({} bytes)", path.display(), html.len());
                ExitCode::SUCCESS
            }
            Err(e) => err_exit2(format!(
                "fluxmirror {subcmd}: writing {}: {e}",
                path.display()
            )),
        },
    }
}

/// `/tmp/fluxmirror-<subcmd>-<YYYY-MM-DD-HHMMSS>.html`. The timestamp
/// is UTC so two cards rendered seconds apart never collide regardless
/// of the user's timezone.
pub fn auto_out_path(subcmd: &str) -> PathBuf {
    let now = Utc::now();
    let ts = now.format("%Y-%m-%d-%H%M%S");
    let filename = format!("fluxmirror-{}-{}.html", subcmd, ts);
    PathBuf::from("/tmp").join(filename)
}

/// `--out -` is the conventional "write to stdout" sentinel; we accept
/// it anywhere a `--out PATH` is valid.
fn is_stdout_sentinel(path: &Path) -> bool {
    path.as_os_str() == "-"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn auto_out_path_starts_with_tmp_and_subcmd() {
        let p = auto_out_path("today");
        let s = p.to_string_lossy();
        assert!(s.starts_with("/tmp/fluxmirror-today-"));
        assert!(s.ends_with(".html"));
    }

    #[test]
    fn stdout_sentinel_detected() {
        assert!(is_stdout_sentinel(Path::new("-")));
        assert!(!is_stdout_sentinel(Path::new("/tmp/foo.html")));
    }
}
