// Snapshot test for the M5 option A weekly HTML digest card.
//
// Builds a deterministic `WeekHtmlStats` (no DB, no system clock, no
// version-stamped footer) and renders it through `render_card` for two
// languages. The rendered output is compared byte-for-byte against the
// committed `tests/snapshots/week_html_{en,ko}.html` fixtures.
//
// If a renderer change is intended, regenerate the snapshots with:
//   cargo test --test report_week_html -- --ignored update_snapshots
// then re-run the suite. The hash assertions below use a stable
// SHA-256 over the same fixture; if the snapshot file moves, that hash
// must be updated alongside it.

use std::path::PathBuf;
use std::process::Command;

use chrono::NaiveDate;
use fluxmirror_cli::cmd::report::html::{render_card, AgentRow, WeekHtmlStats};
use fluxmirror_core::report::pack;

/// Build the deterministic fixture both snapshot variants share.
///
/// 2 agents, 5 active days, varied hours, varied files. The footer is
/// pinned to a string the production code would never produce so any
/// drift between fixture and renderer is obvious.
fn fixture_stats() -> WeekHtmlStats {
    // Heatmap: 24x7. Pre-seed with a varied pattern.
    // Day-of-week index 0=Mon..6=Sun.
    // Mon 09:00 = 3, 10:00 = 5
    // Tue 14:00 = 7
    // Wed 11:00 = 2
    // Thu 09:00 = 4, 16:00 = 6
    // Fri 13:00 = 1
    // Sat / Sun: empty
    let mut heatmap = [[0u32; 24]; 7];
    heatmap[0][9] = 3;
    heatmap[0][10] = 5;
    heatmap[1][14] = 7;
    heatmap[2][11] = 2;
    heatmap[3][9] = 4;
    heatmap[3][16] = 6;
    heatmap[4][13] = 1;

    let agent_summary = vec![
        AgentRow {
            agent: "claude-code".into(),
            calls: 18,
            sessions: 4,
            active_days: 5,
            top_tool: "Bash".into(),
        },
        AgentRow {
            agent: "gemini-cli".into(),
            calls: 10,
            sessions: 2,
            active_days: 3,
            top_tool: "read_file".into(),
        },
    ];

    let top_files = vec![
        ("src/cmd/report/week.rs".into(), 7u32),
        ("README.md".into(), 5),
        ("Cargo.toml".into(), 3),
    ];

    let top_shells = vec![
        ("cargo test --workspace".into(), 4u32),
        ("git push origin main".into(), 2),
    ];

    WeekHtmlStats {
        range_start: NaiveDate::from_ymd_opt(2026, 4, 21).unwrap(),
        range_end: NaiveDate::from_ymd_opt(2026, 4, 27).unwrap(),
        tz_label: "UTC".into(),
        heatmap,
        agent_summary,
        top_files,
        top_shells,
        // Total dow weight: Mon=8, Tue=7, Wed=2, Thu=10, Fri=1, Sat=0, Sun=0
        // → busiest = Thursday (index 3) with 10 calls.
        busiest_day_dow: 3,
        busiest_day_calls: 10,
        heaviest_tool: "Bash".into(),
        heaviest_tool_calls: 12,
        total_calls: 28,
        total_agents: 2,
        // Pinned to a stable, non-version-stamped string so the snapshot
        // hash never moves with the workspace version bump.
        generated_footer: "Generated by fluxmirror SNAPSHOT - 2026-04-27T00:00:00Z".into(),
    }
}

/// Workspace root, derived from the CARGO_MANIFEST_DIR of this crate.
/// `report_week_html.rs` lives in `crates/fluxmirror-cli/tests/`, so the
/// manifest dir is `crates/fluxmirror-cli/`.
fn snapshot_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("snapshots")
        .join(name)
}

/// Re-implementation of the canonical SHA-256 over an arbitrary byte
/// slice, written out by hand so the test crate doesn't pull in a hash
/// dependency. Returns the lowercase hex digest.
fn sha256_hex(input: &[u8]) -> String {
    // Constants for SHA-256.
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];

    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    ];

    // Pre-process: padding + length.
    let mut msg = input.to_vec();
    let bit_len = (input.len() as u64).wrapping_mul(8);
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([
                chunk[i * 4],
                chunk[i * 4 + 1],
                chunk[i * 4 + 2],
                chunk[i * 4 + 3],
            ]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let mut a = h[0];
        let mut b = h[1];
        let mut c = h[2];
        let mut d = h[3];
        let mut e = h[4];
        let mut f = h[5];
        let mut g = h[6];
        let mut hh = h[7];
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }
    let mut out = String::with_capacity(64);
    for v in h {
        out.push_str(&format!("{:08x}", v));
    }
    out
}

#[test]
fn render_card_starts_with_doctype_and_closes_html() {
    let lp = pack("english");
    let out = render_card(&fixture_stats(), lp);
    assert!(out.starts_with("<!DOCTYPE html>"), "got: {}", &out[..50]);
    assert!(out.contains("</html>"));
    assert!(out.contains("fluxmirror weekly digest"));
}

#[test]
fn render_card_contains_every_fixture_agent_name() {
    let lp = pack("english");
    let out = render_card(&fixture_stats(), lp);
    for agent in &["claude-code", "gemini-cli"] {
        assert!(out.contains(agent), "missing agent {agent}");
    }
}

#[test]
fn english_snapshot_matches_committed_fixture() {
    let lp = pack("english");
    let rendered = render_card(&fixture_stats(), lp);
    let snap_path = snapshot_path("week_html_en.html");
    let expected = std::fs::read_to_string(&snap_path).unwrap_or_else(|e| {
        panic!(
            "missing snapshot {}: {e}\n\
             Regenerate with: SNAPSHOT_UPDATE=1 cargo test --test report_week_html",
            snap_path.display()
        )
    });
    if std::env::var_os("SNAPSHOT_UPDATE").is_some() {
        std::fs::write(&snap_path, &rendered).unwrap();
        return;
    }
    assert_eq!(
        rendered, expected,
        "english HTML snapshot drift — \
         re-run with SNAPSHOT_UPDATE=1 if intended"
    );
}

#[test]
fn korean_snapshot_matches_committed_fixture() {
    let lp = pack("korean");
    let rendered = render_card(&fixture_stats(), lp);
    let snap_path = snapshot_path("week_html_ko.html");
    let expected = std::fs::read_to_string(&snap_path).unwrap_or_else(|e| {
        panic!(
            "missing snapshot {}: {e}\n\
             Regenerate with: SNAPSHOT_UPDATE=1 cargo test --test report_week_html",
            snap_path.display()
        )
    });
    if std::env::var_os("SNAPSHOT_UPDATE").is_some() {
        std::fs::write(&snap_path, &rendered).unwrap();
        return;
    }
    assert_eq!(
        rendered, expected,
        "korean HTML snapshot drift — \
         re-run with SNAPSHOT_UPDATE=1 if intended"
    );
}

#[test]
fn english_snapshot_hash_is_stable() {
    let snap_path = snapshot_path("week_html_en.html");
    let bytes = std::fs::read(&snap_path).expect("snapshot must exist for hash check");
    let digest = sha256_hex(&bytes);
    // The hash here is derived from the committed snapshot bytes — any
    // intentional renderer change updates BOTH the .html file AND this
    // string in the same commit.
    let expected = include_str!("snapshots/week_html_en.sha256").trim();
    assert_eq!(
        digest, expected,
        "english snapshot SHA-256 drift — \
         update tests/snapshots/week_html_en.sha256 if the renderer change is intended"
    );
}

#[test]
fn cli_format_html_writes_doctype_to_stdout() {
    // End-to-end: spawn the binary against an empty DB, ask for HTML,
    // and confirm we get a complete document on stdout. The empty-DB
    // path still emits the full skeleton (with the empty-summary line).
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("events.db");
    let _store = fluxmirror_store::SqliteStore::open(&path).unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_fluxmirror"))
        .args(["week", "--tz", "UTC", "--lang", "english", "--format", "html"])
        .arg("--db")
        .arg(&path)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "non-zero exit: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.starts_with("<!DOCTYPE html>"), "got: {}", &stdout[..50.min(stdout.len())]);
    assert!(stdout.contains("</html>"));
    assert!(stdout.contains("fluxmirror weekly digest"));
}

#[test]
fn cli_format_html_with_out_writes_file_and_prints_confirmation() {
    let dir = tempfile::tempdir().unwrap();
    let db = dir.path().join("events.db");
    let _store = fluxmirror_store::SqliteStore::open(&db).unwrap();
    let out = dir.path().join("card.html");

    let output = Command::new(env!("CARGO_BIN_EXE_fluxmirror"))
        .args(["week", "--tz", "UTC", "--lang", "english", "--format", "html"])
        .arg("--db")
        .arg(&db)
        .arg("--out")
        .arg(&out)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "non-zero exit: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(
        stdout.starts_with("wrote "),
        "expected 'wrote ...' confirmation, got: {stdout}"
    );
    assert!(stdout.contains("bytes)"), "missing bytes suffix: {stdout}");

    let body = std::fs::read_to_string(&out).unwrap();
    assert!(body.starts_with("<!DOCTYPE html>"));
    assert!(body.contains("</html>"));
}

#[test]
fn cli_other_reports_reject_html_with_exit_two() {
    // M5 only ships --format html for `week`. The other six reports
    // must keep returning exit 2 with a "not yet implemented" line.
    for sub in &["today", "yesterday", "agents", "compare", "about"] {
        let output = Command::new(env!("CARGO_BIN_EXE_fluxmirror"))
            .args([sub, "--lang", "english", "--format", "html"])
            .output()
            .unwrap();
        assert!(
            !output.status.success(),
            "expected exit 2 for {sub} --format html"
        );
        assert_eq!(output.status.code(), Some(2));
        let stderr = String::from_utf8(output.stderr).unwrap();
        assert!(
            stderr.contains("not yet implemented"),
            "{sub}: missing 'not yet implemented' in stderr: {stderr}"
        );
    }
}

#[test]
fn sha256_smoke_matches_well_known_inputs() {
    // Belt-and-suspenders: empty input has a hard-coded hash. Any
    // arithmetic regression in the local SHA-256 would tank both this
    // test and the snapshot hash test together.
    assert_eq!(
        sha256_hex(b""),
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );
    assert_eq!(
        sha256_hex(b"abc"),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
}
