// Integration tests for the M5.1 "Shipped this week" git narrative.
//
// Covers:
//   1. Real-git fixture: temp repo with three commits, assert subjects
//      and ordering match `git log` defaults (newest first).
//   2. Non-git directory degrades to an empty narrative.
//   3. Two cwds inside the same repo dedup to one entry.
//   4. HTML render: narrative section appears with both repos and all
//      commit subjects.
//   5. HTML render: narrative omitted when empty.

use chrono::{DateTime, Utc};
use std::path::PathBuf;
use std::process::Command as StdCommand;

use chrono::NaiveDate;
use fluxmirror_cli::cmd::report::git_narrative::{collect, GitNarrative, RepoCommits};
use fluxmirror_cli::cmd::report::html::{render_card, AgentRow, WeekHtmlStats};
use fluxmirror_core::report::pack;
use tempfile::TempDir;

fn git_available() -> bool {
    StdCommand::new("git").arg("--version").output().is_ok()
}

fn init_repo(dir: &std::path::Path) -> bool {
    if !git_available() {
        return false;
    }
    for argv in [
        vec!["init", "-q", "-b", "main"],
        vec!["config", "user.email", "test@example.test"],
        vec!["config", "user.name", "test"],
        vec!["config", "commit.gpgsign", "false"],
    ] {
        let st = StdCommand::new("git")
            .args(&argv)
            .current_dir(dir)
            .status();
        if !matches!(st, Ok(s) if s.success()) {
            return false;
        }
    }
    true
}

fn make_commit(dir: &std::path::Path, file: &str, subject: &str) {
    std::fs::write(dir.join(file), subject).unwrap();
    let st = StdCommand::new("git")
        .args(["add", file])
        .current_dir(dir)
        .status()
        .unwrap();
    assert!(st.success(), "git add failed");
    let st = StdCommand::new("git")
        .args(["commit", "-q", "--no-gpg-sign", "-m", subject])
        .current_dir(dir)
        .status()
        .unwrap();
    assert!(st.success(), "git commit failed for {subject}");
}

fn wide_window() -> (DateTime<Utc>, DateTime<Utc>) {
    (
        "2000-01-01T00:00:00Z".parse().unwrap(),
        "2099-12-31T23:59:59Z".parse().unwrap(),
    )
}

#[test]
fn fixture_repo_with_three_commits_round_trips() {
    let dir = TempDir::new().unwrap();
    if !init_repo(dir.path()) {
        eprintln!("skipping: git not available");
        return;
    }
    make_commit(dir.path(), "a.txt", "feat: first");
    make_commit(dir.path(), "b.txt", "fix: second");
    make_commit(dir.path(), "c.txt", "docs: third");

    let (since, until) = wide_window();
    let cwd = dir.path().display().to_string();
    let n = collect(&[cwd], since, until, None);

    assert_eq!(n.repos.len(), 1, "expected exactly one repo: {:?}", n.repos);
    let r = &n.repos[0];
    assert_eq!(r.total_commits, 3);
    assert_eq!(r.commits.len(), 3);
    assert_eq!(r.commits[0], "docs: third");
    assert_eq!(r.commits[1], "fix: second");
    assert_eq!(r.commits[2], "feat: first");
    let basename = dir.path().file_name().unwrap().to_str().unwrap();
    assert_eq!(r.repo_name, basename);
}

#[test]
fn non_git_directory_yields_empty_narrative() {
    let dir = TempDir::new().unwrap();
    let (since, until) = wide_window();
    let cwd = dir.path().display().to_string();
    let n = collect(&[cwd], since, until, None);
    assert!(n.repos.is_empty());
}

#[test]
fn dedup_two_cwds_to_same_repo() {
    let dir = TempDir::new().unwrap();
    if !init_repo(dir.path()) {
        eprintln!("skipping: git not available");
        return;
    }
    let sub = dir.path().join("nested");
    std::fs::create_dir(&sub).unwrap();
    make_commit(dir.path(), "x.txt", "feat: only");

    let (since, until) = wide_window();
    let cwds = vec![
        dir.path().display().to_string(),
        sub.display().to_string(),
    ];
    let n = collect(&cwds, since, until, None);
    assert_eq!(n.repos.len(), 1);
    assert_eq!(n.repos[0].total_commits, 1);
}

fn html_fixture_with_narrative(narrative: Option<GitNarrative>) -> WeekHtmlStats {
    let mut heatmap = [[0u32; 24]; 7];
    heatmap[1][14] = 7;
    WeekHtmlStats {
        range_start: NaiveDate::from_ymd_opt(2026, 4, 21).unwrap(),
        range_end: NaiveDate::from_ymd_opt(2026, 4, 27).unwrap(),
        tz_label: "UTC".into(),
        heatmap,
        agent_summary: vec![AgentRow {
            agent: "claude-code".into(),
            calls: 7,
            sessions: 1,
            active_days: 1,
            top_tool: "Bash".into(),
        }],
        top_files: vec![("README.md".into(), 1u32)],
        top_shells: vec![("ls".into(), 1u32)],
        busiest_day_dow: 1,
        busiest_day_calls: 7,
        heaviest_tool: "Bash".into(),
        heaviest_tool_calls: 7,
        total_calls: 7,
        total_agents: 1,
        generated_footer: "Generated by fluxmirror SNAPSHOT - 2026-04-27T00:00:00Z".into(),
        narrative,
    }
}

#[test]
fn html_render_includes_narrative_section_with_two_repos() {
    let lp = pack("english");
    let narrative = GitNarrative {
        repos: vec![
            RepoCommits {
                repo_name: "alpha".into(),
                repo_path: PathBuf::from("/tmp/alpha"),
                commits: vec![
                    "feat: alpha-1".into(),
                    "fix: alpha-2".into(),
                    "docs: alpha-3".into(),
                ],
                total_commits: 3,
            },
            RepoCommits {
                repo_name: "beta".into(),
                repo_path: PathBuf::from("/tmp/beta"),
                commits: vec![
                    "feat: beta-1".into(),
                    "fix: beta-2".into(),
                    "docs: beta-3".into(),
                ],
                total_commits: 3,
            },
        ],
    };
    let stats = html_fixture_with_narrative(Some(narrative));
    let html = render_card(&stats, lp);
    assert!(html.contains("class=\"narrative\""), "missing narrative class");
    assert!(html.contains("Shipped this week"));
    for needle in &[
        "alpha",
        "beta",
        "feat: alpha-1",
        "fix: alpha-2",
        "docs: alpha-3",
        "feat: beta-1",
        "fix: beta-2",
        "docs: beta-3",
    ] {
        assert!(html.contains(needle), "missing {needle}");
    }
}

#[test]
fn html_render_omits_section_when_narrative_empty() {
    let lp = pack("english");
    let stats = html_fixture_with_narrative(Some(GitNarrative { repos: vec![] }));
    let html = render_card(&stats, lp);
    assert!(
        !html.contains("class=\"narrative\""),
        "expected no narrative section in empty case"
    );
    assert!(!html.contains("Shipped this week"));
}
