// M5.3 — business-grade weekly HTML card sections.
//
// Covers the four new synthesised blocks:
//   * Week Summary (3 bullets)
//   * Daily Breakdown (7-row table with theme cells)
//   * Highlights (3-5 bullets)
//   * Insights (4 bullets)
//
// All assertions are over deterministic, hand-built fixtures so the
// suite stays portable (no DB, no clock, no network). Snapshot drift
// is covered by the sibling `report_week_html` suite.

use chrono::NaiveDate;
use fluxmirror_cli::cmd::report::html::{render_card, AgentRow, WeekHtmlStats};
use fluxmirror_cli::cmd::report::week_summary::{
    classify_theme, format_active_days, DailyRow, DayTheme, Highlights, Insights, ProjectShare,
    WeekSummary,
};
use fluxmirror_core::report::pack;

/// Build a deterministic 7-row breakdown for a "weekend sprint" week
/// — Sat 800 calls, Sun 1500 calls, Mon-Fri idle.
fn weekend_sprint_breakdown() -> Vec<DailyRow> {
    let mon = NaiveDate::from_ymd_opt(2026, 4, 20).unwrap();
    let mut rows = Vec::with_capacity(7);
    for i in 0..5 {
        let d = mon.checked_add_signed(chrono::Duration::days(i)).unwrap();
        rows.push(DailyRow {
            date: d,
            dow_label: ["Mon", "Tue", "Wed", "Thu", "Fri"][i as usize].into(),
            calls: 0,
            new_files: 0,
            edited_files: 0,
            agents_active: 0,
            theme: DayTheme::Idle,
        });
    }
    rows.push(DailyRow {
        date: NaiveDate::from_ymd_opt(2026, 4, 25).unwrap(),
        dow_label: "Sat".into(),
        calls: 800,
        new_files: 60,
        edited_files: 30,
        agents_active: 3,
        theme: DayTheme::Building,
    });
    rows.push(DailyRow {
        date: NaiveDate::from_ymd_opt(2026, 4, 26).unwrap(),
        dow_label: "Sun".into(),
        calls: 1500,
        new_files: 100,
        edited_files: 63,
        agents_active: 3,
        theme: DayTheme::Shipping,
    });
    rows
}

fn business_fixture() -> WeekHtmlStats {
    let daily = weekend_sprint_breakdown();
    let summary = WeekSummary {
        total_calls: 2300,
        active_days: 2,
        active_days_label: "Sat-Sun".into(),
        primary_project: Some(ProjectShare {
            name: "fluxmirror".into(),
            calls: 2231,
            share_pct: 97,
        }),
        weekly_theme: "Weekend sprint - shipping focus".into(),
    };
    let highlights = Highlights {
        work_pattern: "Sat-Sun work pattern - 2300 total calls in window".into(),
        active_feature_area: Some(
            "Ongoing focus: cmd/report - week.rs (14), html.rs (12), week_summary.rs (41)".into(),
        ),
        hot_spine_files: vec![
            ("progress.md".into(), 44),
            ("week.rs".into(), 14),
            ("html.rs".into(), 12),
        ],
        agent_breakdown: "claude-code dominance - 2100 calls / 8 sessions vs gemini-cli 200"
            .into(),
        project_breakdown: None,
    };
    let insights = Insights {
        busiest_day: Some((NaiveDate::from_ymd_opt(2026, 4, 26).unwrap(), 1500, 100, 63)),
        edit_to_new_ratio: Some((95, 178, 1.873)),
        project_focus_pct: Some(97),
        mcp_traffic_label: "active (100 msgs)".into(),
    };

    WeekHtmlStats {
        range_start: NaiveDate::from_ymd_opt(2026, 4, 20).unwrap(),
        range_end: NaiveDate::from_ymd_opt(2026, 4, 26).unwrap(),
        tz_label: "UTC".into(),
        heatmap: [[0u32; 24]; 7],
        agent_summary: vec![AgentRow {
            agent: "claude-code".into(),
            calls: 2100,
            sessions: 8,
            active_days: 2,
            top_tool: "Bash".into(),
        }],
        top_files: vec![("progress.md".into(), 44u32)],
        top_shells: vec![("cargo test".into(), 12u32)],
        busiest_day_dow: 6,
        busiest_day_calls: 1500,
        heaviest_tool: "Bash".into(),
        heaviest_tool_calls: 800,
        total_calls: 2300,
        total_agents: 1,
        generated_footer: "Generated by fluxmirror SNAPSHOT - 2026-04-27T00:00:00Z".into(),
        narrative: None,
        summary,
        daily_breakdown: daily,
        highlights,
        insights,
    }
}

#[test]
fn theme_classifier_table_covers_all_five_outcomes() {
    let cases: &[(u32, u32, u32, DayTheme)] = &[
        (0, 0, 0, DayTheme::Idle),
        (5, 0, 0, DayTheme::Light),
        (49, 10, 5, DayTheme::Light),
        (200, 50, 20, DayTheme::Building),
        (200, 5, 30, DayTheme::Polishing),
        (1500, 80, 30, DayTheme::Shipping),
    ];
    for (calls, new, edited, want) in cases {
        let got = classify_theme(*calls, *new, *edited);
        assert_eq!(
            got, *want,
            "calls={calls}, new={new}, edited={edited}: got {:?}, want {:?}",
            got, want
        );
    }
}

#[test]
fn daily_breakdown_renders_seven_rows_with_theme_cells() {
    let lp = pack("english");
    let stats = business_fixture();
    let html = render_card(&stats, lp);
    // Section heading.
    assert!(html.contains("daily-breakdown"), "missing daily-breakdown section class");
    assert!(html.contains("Daily Breakdown"), "missing daily-breakdown heading");
    // Theme labels for the two active days.
    assert!(html.contains("building"), "missing building theme cell");
    assert!(html.contains("shipping"), "missing shipping theme cell");
    // Idle days use the idle theme color.
    assert!(html.contains("#f3f4f6"), "missing idle theme color");
    // Shipping cell uses the shipping accent.
    assert!(html.contains("#10b981"), "missing shipping color");
    // Theme suffix when ≥2 agents.
    assert!(html.contains("3 agents"), "missing per-day agent suffix");
    // Seven date rows in the table — count the date format.
    assert_eq!(
        html.matches("2026-04-").count() >= 7,
        true,
        "expected at least 7 dates in the daily breakdown table"
    );
}

#[test]
fn week_summary_block_shows_total_calls_and_primary_project() {
    let lp = pack("english");
    let stats = business_fixture();
    let html = render_card(&stats, lp);
    assert!(html.contains("week-summary"), "missing week-summary section");
    assert!(html.contains("Week Summary"), "missing summary heading");
    assert!(html.contains("2300"), "missing total-call count");
    assert!(html.contains("Sat-Sun"), "missing active-days label");
    assert!(html.contains("fluxmirror"), "missing project name");
    assert!(html.contains("97%"), "missing project share %");
    assert!(
        html.contains("Weekly theme:"),
        "missing weekly-theme lead-bold"
    );
    assert!(
        html.contains("Weekend sprint"),
        "weekly theme should mention the weekend pattern"
    );
}

#[test]
fn highlights_section_emits_lead_bold_bullets() {
    let lp = pack("english");
    let stats = business_fixture();
    let html = render_card(&stats, lp);
    assert!(html.contains("highlights"), "missing highlights section class");
    assert!(html.contains("Highlights"), "missing highlights heading");
    assert!(html.contains("<strong>Work pattern"), "missing pattern lead");
    assert!(html.contains("<strong>Hot spine"), "missing hot spine lead");
    assert!(
        html.contains("<strong>Active feature area"),
        "missing active feature area lead"
    );
    assert!(
        html.contains("Sat-Sun work pattern"),
        "missing work-pattern body"
    );
}

#[test]
fn insights_section_renders_busiest_day_and_mcp() {
    let lp = pack("english");
    let stats = business_fixture();
    let html = render_card(&stats, lp);
    assert!(html.contains("insights"), "missing insights section class");
    assert!(html.contains("Busiest day"), "missing busiest-day insight");
    assert!(html.contains("Sun"), "missing DOW in busiest-day");
    assert!(html.contains("1500"), "missing busiest-day call count");
    assert!(
        html.contains("Edit-to-new ratio"),
        "missing edit-ratio insight"
    );
    assert!(
        html.contains("MCP traffic"),
        "missing MCP-traffic insight"
    );
    assert!(
        html.contains("active (100 msgs)"),
        "MCP active label should appear"
    );
}

#[test]
fn mcp_traffic_thresholds_route_to_correct_label() {
    // Build three fixtures that vary only the mcp_traffic_label and
    // assert the rendered HTML reflects each bucket's phrasing.
    let lp = pack("english");

    let mut none = business_fixture();
    none.insights.mcp_traffic_label = "none - proxy not active".into();
    let html = render_card(&none, lp);
    assert!(html.contains("MCP traffic"), "MCP heading missing in 'none'");
    assert!(html.contains("none"), "expected 'none' phrasing in MCP label");

    let mut light = business_fixture();
    light.insights.mcp_traffic_label = "light (25 msgs)".into();
    let html = render_card(&light, lp);
    assert!(html.contains("light"), "expected 'light' phrasing in MCP label");
    assert!(html.contains("25 msgs"), "expected msg count in light label");

    let mut active = business_fixture();
    active.insights.mcp_traffic_label = "active (100 msgs)".into();
    let html = render_card(&active, lp);
    assert!(html.contains("active"), "expected 'active' phrasing");
    assert!(html.contains("100 msgs"));
}

#[test]
fn weekend_only_pattern_label_localises() {
    let lp_en = pack("english");
    let mon = NaiveDate::from_ymd_opt(2026, 4, 20).unwrap();
    let sat = NaiveDate::from_ymd_opt(2026, 4, 25).unwrap();
    let sun = NaiveDate::from_ymd_opt(2026, 4, 26).unwrap();
    assert_eq!(format_active_days(&[sat, sun], lp_en), "Sat-Sun");
    let weekdays: Vec<NaiveDate> = (0..5)
        .map(|i| mon.checked_add_signed(chrono::Duration::days(i)).unwrap())
        .collect();
    assert_eq!(format_active_days(&weekdays, lp_en), "Mon-Fri");

    let lp_ko = pack("korean");
    assert_eq!(format_active_days(&[sat, sun], lp_ko), "토-일");
}

#[test]
fn korean_pack_translates_section_headings() {
    let lp = pack("korean");
    let stats = business_fixture();
    let html = render_card(&stats, lp);
    assert!(html.contains("주간 요약"), "missing ko summary heading");
    assert!(html.contains("일별 분석"), "missing ko daily heading");
    assert!(html.contains("주요 활동"), "missing ko highlights heading");
    assert!(html.contains("인사이트"), "missing ko insights heading");
}

#[test]
fn html_size_under_thirty_kb() {
    let lp = pack("english");
    let stats = business_fixture();
    let html = render_card(&stats, lp);
    assert!(
        html.len() <= 30 * 1024,
        "card too big: {} bytes (cap 30 KiB)",
        html.len()
    );
}
